# Generated by Django 3.2.5 on 2021-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_news_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('publish', 'Может p1'),)},
        ),
    ]
