# Generated by Django 3.2.5 on 2021-07-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('publish_news', 'Может p12'),)},
        ),
    ]
